<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Friday, August 22, 2025 4:21:38 PM</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "C:\Users\pmedi\Documents\00_final_project\Road-Accident-Hotspot\Tool\main.py", line 70, in &lt;module&gt;
﻿    field_map = field_mappings.getFieldMap(field_index)
﻿                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "C:\Users\pmedi\AppData\Local\Programs\ArcGIS\Pro\Resources\ArcPy\arcpy\arcobjects\arcobjects.py", line 866, in getFieldMap
﻿    return convertArcObjectToPythonObject(self._arc_object.GetFieldMap(*gp_fixargs(args)))
﻿                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿RuntimeError: FieldMappings: Error in getting field map from field mapping for GetFieldMap
</msg><msg code="0" type="0">Failed script Road Crash Hotspot...</msg><msg code="-2147467259" type="100">Failed to execute (RoadCrashHotspot).</msg><msg code="0" type="3">Failed at Friday, August 22, 2025 4:21:40 PM (Elapsed Time: 2.02 seconds)</msg></messages>