<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Friday, August 22, 2025 7:04:03 PM</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "C:\Users\pmedi\Documents\00_final_project\Road-Accident-Hotspot\Tool\main.py", line 59, in &lt;module&gt;
﻿    arcpy.edit.Snap(snapped_points, [snap_environment_1,snap_environment_2]) # Snap the copied crash data to the road network
﻿    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "C:\Users\pmedi\AppData\Local\Programs\ArcGIS\Pro\Resources\ArcPy\arcpy\edit.py", line 409, in Snap
﻿    raise e
﻿  File "C:\Users\pmedi\AppData\Local\Programs\ArcGIS\Pro\Resources\ArcPy\arcpy\edit.py", line 406, in Snap
﻿    retval = convertArcObjectToPythonObject(gp.Snap_edit(*gp_fixargs((in_features, snap_environment), True)))
﻿                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "C:\Users\pmedi\AppData\Local\Programs\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 533, in &lt;lambda&gt;
﻿    return lambda *args: val(*gp_fixargs(args, True))
﻿                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿RuntimeError: Object: Error in executing tool
</msg><msg code="0" type="0">Failed script Road Crash Hotspot...</msg><msg code="-2147467259" type="100">Failed to execute (RoadCrashHotspot).</msg><msg code="0" type="3">Failed at Friday, August 22, 2025 7:04:07 PM (Elapsed Time: 3.77 seconds)</msg></messages>